# Finding the 1-D filter

In [3]:
inp = [12, 20, 3, 10, 22, 19, 23, 16, 0, 21, 23, 16, 18]
inp_size = size(inp,2)


inp =

    12    20     3    10    22    19    23    16     0    21    23    16    18


inp_size =

    13



In [4]:
out = [75, 52, 33, 97, 251, 211, 63, 65]
out_size = size(out,2)


out =

    75    52    33    97   251   211    63    65


out_size =

     8



### Method:

- Using Linear regressio we will try to find the filter
- Hence we are assuming random values in beginning

- We will calculate the pred_out 
- We will find the loss and gradient

## Using Normalize equations 

In [7]:
% Assuming stride = 1
% Assuming padding = 0
filter_size = (size(inp,2) - size(out,2) + 1);


In [8]:
inp_pred = zeros(filter_size,out_size);
for i = 1:inp_size - filter_size + 1
    inp_pred(:,i) = inp(i:i+filter_size-1);
end
inp_pred


inp_pred =

    12    20     3    10    22    19    23    16
    20     3    10    22    19    23    16     0
     3    10    22    19    23    16     0    21
    10    22    19    23    16     0    21    23
    22    19    23    16     0    21    23    16
    19    23    16     0    21    23    16    18



In [9]:
filter = out*pinv(inp_pred)


filter =

    5.0000    4.0000    4.0000   -3.0000   -3.0000    1.0000



## Using Gradient Desent

In [10]:
epoch = 1000; 
lr = 0.001;
FILTER = rand(1,filter_size).*10


FILTER =

    8.1472    9.0579    1.2699    9.1338    6.3236    0.9754



In [18]:
for ind = 1:epoch

out_pred = FILTER*inp_pred;
loss = sum((out - out_pred).^2)/(2*out_size);
gradient = (out_pred - out)*inp_pred'/out_size;
FILTER = FILTER - lr.*gradient;

end

In [16]:
FILTER = round(FILTER)
out_pred = FILTER*inp_pred
out


FILTER =

     5     4     4    -3    -3     1


out_pred =

    75    52    33    97   251   211    63    65


out =

    75    52    33    97   251   211    63    65



In [17]:
FILTER = flip(FILTER)


FILTER =

     1    -3    -3     4     4     5

